name: Publish Python Package

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine
          
      - name: Build package
        run: python -m build
        
      - name: Configure PyPI credentials
        run: |
          echo "[testpypi]" > ~/.pypirc
          echo "repository = https://test.pypi.org/legacy/" >> ~/.pypirc
          echo "username = __token__" >> ~/.pypirc
          echo "password = ${{ secrets.TEST_PYPI_API_TOKEN }}" >> ~/.pypirc
          echo "[github]" >> ~/.pypirc
          echo "repository = https://maven.pkg.github.com/australmetrics/pascal-ndvi-block" >> ~/.pypirc
          echo "username = ${{ github.actor }}" >> ~/.pypirc
          echo "password = ${{ secrets.GITHUB_TOKEN }}" >> ~/.pypirc
        
      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m twine upload --repository github dist/*
