name: Validate Manifest

on:
  push:
    paths:
      - 'manifest.json'
      - 'schemas/**'
  pull_request:
    paths:
      - 'manifest.json'
      - 'schemas/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install check-jsonschema
        run: pip install check-jsonschema
      
      - name: Validate manifest.json
        run: check-jsonschema --schemafile schemas/manifest.schema.json manifest.json
